#!/bin/bash

RunMpdIfNotRunning()
{
    mpc status &> /dev/null

    if [ $? -gt 0 ]
    then
        mpd &> /dev/null
        
        if [ $? -gt 0 ]
        then
            echo "error!"
            echo "mpd hasn't started correctly."
            echo "exit."
            exit 69
        fi
    fi
}

Play()
{
    case $(mpc status | grep -o '^\[[a-z]*\]' | grep -o '[a-z]*') in
        "paused")
            mpc play
            ;;
        "playing")
            Pause
            ;;
        *)
            mpc play
            ;;
    esac
}

Pause()
{
    mpc pause
}

Stop()
{
    case $(mpc status | grep -o '^\[[a-z]*\]' | grep -o '[a-z]*') in
        "paused")
            mpc stop
            ;;
        "playing")
            mpc stop
            ;;
        "")
            mpc play
            ;;
        *)
            mpc play
            ;;
    esac
}

Next()
{
    mpc next
}

Prev()
{
    mpc prev
}

SeekPlus()
{
    mpc seek +5
}

SeekMin()
{
    mpc seek -5
}

Status()
{
    mpc status
}

Player()
{
    case $1 in
    "ncmpcpp")
        echo "hello"
        gnome-terminal --hide-menubar --title="ncmpcpp" -e ncmpcpp &> /dev/null &
        exit 0
        ;;
    "sonata")
        /opt/sonata/run-sonata &> /dev/null &
        
        if [ $? -gt 0 ]
        then
            exit 7
        fi
        
        exit 0
        ;;
    esac
}

RunMpdIfNotRunning

case $1 in
    "play")
        Play
        ;;
    "pause")
        Pause
        ;;
    "next")
        Next
        ;;
    "prev")
        Prev
        ;;
    "stop")
        Stop
        ;;
    "status")
        Status
        ;;
    "seek-plus")
        SeekPlus
        ;;
    "seek-min")
        SeekMin
        ;;
    "sonata" | "ncmpcpp")
        Player $1
        ;;
esac
