#!/bin/bash

SCROT_TMP=/tmp/tynlock-scrot.png
LOCK_TMP=/tmp/tynlock.png

scrot -z $SCROT_TMP

convert $SCROT_TMP -fill black -colorize 40% -filter Gaussian -resize 20% -define filter:sigma=2.5 -resize 500% $LOCK_TMP

rm $SCROT_TMP

i3lock -i $LOCK_TMP -f -e
sleep 5
xset -display $DISPLAY dpms force off

