install :
			cp tele /usr/bin/tele
			chmod 755 /usr/bin/tele
			chown root:root /usr/bin/tele
			cp tele-completion.bash /etc/bash_completion.d/tele-completion.bash
			chown root:root /etc/bash_completion.d/tele-completion.bash
			chmod 644 /etc/bash_completion.d/tele-completion.bash

uninstall :
			rm /usr/bin/tele
			rm /etc/bash_completion.d/tele-completion.bash
